### ISSUE TITLE
Slow, motion is quirky

### ISSUE THREAD

**Issue by mclearc** [minad/mini-popup#3]
Tried this out -- looks pretty good! But it seems noticeably slower than the normal mini buffer or mini-frame. I tried with both vertico and selectrum and noticed the same lag. I also had a problem with motion similar to the other issue here - I use C-j and C-k for motion but for some reason C-k wasn't working.

**Comment by minad** [comment]
Interesting, for me it is fast and mini-frame feels slow. Do you use EXWM or Evil btw?

**Comment by mclearc** [comment]
No EXWM, but yes to evil. EDIT :I'm using General.el for managing keybinds.

And I'm on macOS 10.15.7 Catalina with emacs 28

**Comment by minad** [comment]
Okay, then mini-popup could work for you well. @daviwil also had issues with C-k, maybe some issue with the remaps? See #2.

What is exactly slower or lagging in contrast to mini-frame?

**Comment by mclearc** [comment]
Here's my vertico setup. This works in the normal mini buffer and in mini-frame:

```
(use-package vertico
  :general
  (:keymaps 'vertico-map
   "C-j"    'vertico-next
   "C-k"    'vertico-previous)
  :init
  (vertico-mode)
  :config
  ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
  (setq vertico-cycle t))
```

Typing lags and it is slow to scroll if I'm moving using the C-j key.

**Comment by mclearc** [comment]
I think at least part of the slowness was due to a hook using pulse. Here's what I had:

```
(use-package pulse
  :straight (:type built-in)
  :defer 1
  :commands (pulse-line pulse-momentary-highlight-one-line)
  :config
  (defun pulse-line (&rest _)
    "Pulse the current line."
    (interactive)
    (pulse-momentary-highlight-one-line (point)))

  (dolist (command '(scroll-up-command scroll-down-command
                                       recenter-top-bottom other-window))
    (advice-add command :after #'pulse-line))

  (add-hook 'window-state-change-hook #'pulse-line)
  )
```
Note the `window-state-change-hook`. It was pulsing with every letter typed in the buffer. Removing that makes things more normal (though still maybe not as smooth as the mini buffer).

**Comment by minad** [comment]
> (though still maybe not as smooth as the mini buffer)

Yes, it is not as smooth as the plain minibuffer. Emacs child frames are slow. I have the same problem in Corfu. But from what I've understood the slowness issue has been resolved?

There is still the C-k issue though...

**Comment by mclearc** [comment]
It's less slow but still a bit slow and jumpy. I don't have this issue with mini-frame though. But yes child-frames are definitely not yet fully reliable :) 

Yeah not sure what the C-k problem is, especially since it doesn't just seem to be me.

**Comment by minad** [comment]
@mclearc There were some flicker issues with Corfu (see https://github.com/minad/corfu/issues/37). I added the fix here too, maybe this improves the situation?

**Comment by mclearc** [comment]
Actually mini-popup has been mostly very good. I only notice flicker when I open the popup for the first time after a theme change. After that it is fine. It also seems quite performant now -- I haven't seen any speed issues, and I've resolved the keybinding issue as well. So maybe you can just close this issue?

**Comment by minad** [comment]
Great, thanks!
